---
# test-appserver:
#   hosts:
#     test-appserver:
#       ansible_host: xx.xxx.x.x
#       ansible_connection: ssh
#       ansible_user: centos
test-dbserver:
  hosts:
    test-dbserver1:
      ansible_host: xx.xxx.x.x
      ansible_connection: ssh
      ansible_user: ubuntu
ubuntu_vms:
  hosts:
    test-deb1:
      ansible_host: xx.xxx.x.x
      ansible_connection: ssh
      ansible_user: ubuntu
    test-deb2:
      ansible_host: xx.xxx.x.x
      ansible_connection: ssh
      ansible_user: ubuntu
local:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local

win:
  hosts:
    win1:
      ansible_host: xx.xxx.x.x
      ansible_connection: winrm
      ansible_user: usr
      ansible_password: xxxxxx
      ansible_port: 5986
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: ignore
